version: '3'

services:
  nginx:
    restart: 'no'
    build:
      context: .
      dockerfile: etc/docker/dev/nginx/Dockerfile
    container_name: witrac-backend-test-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/app:delegated
    depends_on:
      - fpm

  fpm:
    restart: 'no'
    container_name: witrac-backend-test-fpm
    build:
      context: .
      dockerfile: etc/docker/dev/php/Dockerfile
    ports:
      - "2222:22"
      - "9090:9000"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: database
    build:
      context: etc/docker/dev/mariadb

    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: witrac
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data:




