version: '3'

services:
  nginx:
    restart: 'no'
    build:
      context: .
      dockerfile: etc/docker/dev/nginx/Dockerfile
    container_name: witrac-backend-test-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/app:delegated
    depends_on:
      - fpm

  fpm:
    restart: 'no'
    container_name: witrac-backend-test-fpm
    build:
      context: .
      dockerfile: etc/docker/dev/php/Dockerfile
    ports:
      - "2222:22"
      - "9090:9000"
    volumes:
      - .:/app:delegated
    env_file:
      - .env

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
