version: '3.5'

services:
  witrac-web:
    container_name: witrac-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 8080:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - witrac-be
    networks:
      - witrac-network

  witrac-be:
    container_name: witrac-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=witrac

    volumes:
      - ./:/appdata/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - witrac-db
    networks:
      - witrac-network

  witrac-db:
    container_name: witrac-db
    build:
      context: ./docker/database
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: witrac_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - witrac-db-data:/var/lib/mysql
    networks:
      - witrac-network

volumes:
  witrac-db-data:

networks:
  witrac-network:
    external: true