#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create-canvas:
  path: /create-canvas-legacy
  controller: App\Controller\IndexController::getCreateCanvas

move:
  path: /move-legacy/{canvasName}/{movementDirection}
  controller: App\Controller\IndexController::getMove


#CANVAS ENDPOINTS
canvas-create:
  path: create-canvas
  controller: App\Controller\Canvas\CreateCanvasController
  methods: [GET]

move-top:
  path: move/{canvasName}/top
  controller: App\Controller\Spaceship\SpaceshipMoveTopController
  methods: [GET]
